language: python
python:
  - "2.7"
  - "3.3"
notifications:
  email: false
before_install:
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - pip install numpy cython dateutil
install:
  - pip install .
script:
  - python -m unittest discover . 'tst*py'